#!/usr/bin/env bash
# network-isolation.sh — Network namespace isolation using slirp4netns
# Sourced by sandbox.sh
#
# Requires: SLIRP4NETNS, COREUTILS, SANDBOX_TMPDIR — provided by sandbox.sh before sourcing.

# Default network addresses used by slirp4netns
SLIRP_GATEWAY="10.0.2.2"
SLIRP_DNS="10.0.2.3"
SLIRP_HOST="10.0.2.15"
SLIRP_NETMASK="255.255.255.0"

# setup_network_isolation BWRAP_PID
#
# Starts slirp4netns against the given bwrap child PID to provide
# userspace networking inside the network namespace.
#
# Sets SLIRP4NETNS_PID to the slirp4netns process PID.
# Sets SLIRP_READY to "1" on success.
#
# The bwrap process MUST have been started with --unshare-net.
setup_network_isolation() {
  local child_pid="$1"

  local slirp_pidfile="${SANDBOX_TMPDIR}/slirp4netns.pid"
  local slirp_ready="${SANDBOX_TMPDIR}/slirp4netns.ready"

  # Start slirp4netns
  # --configure: automatically configure the tap device with IP/routes
  # --mtu 65520: maximize throughput (slirp internal)
  # --disable-host-loopback: block sandbox from reaching host loopback services
  #   (we re-enable access to the proxy port via the gateway address)
  "$SLIRP4NETNS" \
    --configure \
    --mtu 65520 \
    --ready-fd 3 \
    "$child_pid" tap0 \
    3>"$slirp_ready" &

  SLIRP4NETNS_PID=$!

  # Wait for slirp4netns to signal readiness (up to 10 seconds)
  local waited=0
  while [[ ! -s "$slirp_ready" ]] && [[ "$waited" -lt 100 ]]; do
    sleep 0.1
    waited=$((waited + 1))
    # Check if process is still alive
    if ! kill -0 "$SLIRP4NETNS_PID" 2>/dev/null; then
      echo "Error: slirp4netns failed to start" >&2
      return 1
    fi
  done

  if [[ ! -s "$slirp_ready" ]]; then
    echo "Error: slirp4netns did not become ready within 10 seconds" >&2
    kill "$SLIRP4NETNS_PID" 2>/dev/null || true
    return 1
  fi

  SLIRP_READY="1"
  return 0
}

# stop_network_isolation
#
# Stops slirp4netns if it is running.
stop_network_isolation() {
  if [[ -n "${SLIRP4NETNS_PID:-}" ]]; then
    kill "$SLIRP4NETNS_PID" 2>/dev/null || true
    wait "$SLIRP4NETNS_PID" 2>/dev/null || true
    SLIRP4NETNS_PID=""
  fi
}

# generate_resolv_conf TARGET_DIR
#
# Generates a resolv.conf pointing to slirp4netns's DNS resolver.
generate_resolv_conf() {
  local target="$1"
  cat > "$target" << EOF
# Generated by claude-sandbox network isolation
# Points to slirp4netns internal DNS resolver
nameserver ${SLIRP_DNS}
EOF
}
